# Generated by Django 3.2.5 on 2021-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joburl',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobwebsiteurl',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
