# Generated by Django 3.2.5 on 2021-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobwebsite",
            name="visited",
            field=models.BooleanField(default=False),
        ),
    ]
