# Generated by Django 3.2.5 on 2021-12-22 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0002_auto_20210810_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwebsiteurl',
            name='job_title_xpath',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobwebsiteurl',
            name='search_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobwebsiteurl',
            name='visited',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobURL',
        ),
    ]
