# Generated by Django 3.2.5 on 2022-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0002_alter_jobwebsite_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobwebsite",
            name="company_info_xpath",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="jobwebsite",
            name="company_name_xpath",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="jobwebsite",
            name="deadline_xpath",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="jobwebsite",
            name="job_title_page_xpath",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
