# Generated by Django 3.2.5 on 2022-02-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkers", "0003_auto_20220204_1856"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobwebsite",
            name="company_info_xpath",
        ),
        migrations.RemoveField(
            model_name="jobwebsite",
            name="company_name_xpath",
        ),
        migrations.RemoveField(
            model_name="jobwebsite",
            name="deadline_xpath",
        ),
        migrations.RemoveField(
            model_name="jobwebsite",
            name="job_title_page_xpath",
        ),
    ]
