# Generated by Django 3.2.5 on 2021-12-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0003_auto_20211222_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=500)),
                ('search_url', models.CharField(max_length=500)),
                ('visited', models.BooleanField()),
                ('job_title_xpath', models.CharField(max_length=500)),
            ],
        ),
    ]
