# Generated by Django 3.2.5 on 2021-12-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetailsextractor', '0003_auto_20211222_0600'),
        ('checkers', '0004_jobwebsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobWebsiteURL',
        ),
    ]
