# Generated by Django 3.2.5 on 2021-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_access', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
