# Generated by Django 3.2.5 on 2021-12-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkers', '0003_auto_20211222_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWebsiteStrucutre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name_xpath', models.CharField(max_length=1000)),
                ('deadline_xpath', models.DateTimeField()),
                ('c_name_xpath', models.CharField(max_length=1000)),
                ('c_information_xpath', models.CharField(max_length=1000)),
                ('email_xpath', models.CharField(max_length=1000)),
                ('location_xpath', models.CharField(max_length=1000)),
                ('job_description_xpath', models.CharField(max_length=1000)),
                ('salary_xpath', models.CharField(max_length=1000)),
                ('no_vacancy_xpath', models.CharField(max_length=1000)),
                ('level_xpath', models.CharField(max_length=1000)),
                ('qualification_xpath', models.CharField(max_length=1000)),
                ('experience_xpath', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('job_skills', models.TextField()),
                ('company_name', models.TextField()),
                ('company_info', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_location', models.TextField()),
                ('job_description', models.TextField()),
                ('salary', models.IntegerField()),
                ('no_vacancy', models.IntegerField()),
                ('level', models.TextField()),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=500)),
                ('misc_field', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkers.jobwebsiteurl')),
            ],
        ),
    ]
