# Generated by Django 3.2.5 on 2022-02-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobdetailsextractor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteStructure",
        ),
    ]
