# Generated by Django 3.2.5 on 2021-12-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetailsextractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='misc_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_vacancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
