# Generated by Django 3.2.5 on 2021-12-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetailsextractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_location',
            new_name='location',
        ),
    ]
