# Generated by Django 3.2.5 on 2021-12-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetailsextractor', '0002_rename_company_location_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='misc_field',
            new_name='misc',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='no_vacancy',
            new_name='n_vacancy',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
