# Generated by Django 3.2.5 on 2021-12-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetailsextractor', '0003_auto_20211222_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitestructure',
            name='c_information_xpath',
        ),
        migrations.RemoveField(
            model_name='websitestructure',
            name='c_name_xpath',
        ),
        migrations.AddField(
            model_name='websitestructure',
            name='company_description_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='websitestructure',
            name='company_name_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='deadline_xpath',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='email_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='experience_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='job_description_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='level_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='location_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='name_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='no_vacancy_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='qualification_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitestructure',
            name='salary_xpath',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
